#!/usr/bin/env python3
"""Builds the RV32I programs with zig cc and converts them into ROM images.

  sw/tests/<name>.S          -> sw/images/<name>.hex  (bare assembly tests)
  sw/apps/<name>/*.c, *.S    -> sw/images/<name>.hex  (C programs, with crt0)
  sw/images/hello.hex        -> board/de10lite/rom_image_pkg.vhd

zig bundles clang and lld for every target, so a single pip package
(`pip install ziglang`) is the whole cross toolchain. The generated images are
committed; the simulation does not need zig. With --check the images are
rebuilt into a temporary directory and compared with the committed ones.
"""

from __future__ import annotations

import argparse
import filecmp
import os
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rv32i_iss import decode  # noqa: E402  (after the path tweak)

ROOT = Path(__file__).resolve().parent.parent
SW = ROOT / "sw"
COMMON = SW / "common"
IMAGES = SW / "images"
BOARD_PKG = ROOT / "board" / "de10lite" / "rom_image_pkg.vhd"
BOARD_APP = "hello"

ROM_BYTES = 16 * 1024

# generic_rv32 is the bare RV32I base ISA: no M, A, F, C or Zicsr.
COMMON_FLAGS = [
    "-target", "riscv32-freestanding-none", "-mcpu=generic_rv32",
    "-ffreestanding", "-nostdlib", "-fno-stack-protector", "-fno-sanitize=all",
    "-ffunction-sections", "-fdata-sections",
    "-Wall", "-Wextra", "-Werror",
    "-I", str(COMMON),
    "-T", str(COMMON / "link.ld"), "-Wl,--gc-sections",
]
C_FLAGS = ["-std=c11", "-O2"]
# The assembly tests place code at exact distances (.skip), so the linker
# must not shorten instruction sequences behind the assembler's back.
ASM_TEST_FLAGS = ["-mno-relax"]
APP_RUNTIME = [COMMON / "crt0.S", COMMON / "libsoc.c", COMMON / "rt_arith.c"]

SHF_EXECINSTR = 0x4


def find_zig() -> list[str]:
    if os.environ.get("ZIG"):
        return [os.environ["ZIG"]]
    if shutil.which("zig"):
        return ["zig"]
    try:
        import ziglang  # noqa: F401  (pip package that ships the zig binary)
    except ImportError:
        sys.exit("build_sw: zig not found (set ZIG, put zig on PATH or "
                 "`pip install ziglang`)")
    return [sys.executable, "-m", "ziglang"]


def programs() -> dict[str, list[Path]]:
    progs = {p.stem: [p] for p in sorted((SW / "tests").glob("*.S"))}
    for app in sorted(p for p in (SW / "apps").iterdir() if p.is_dir()):
        sources = sorted(app.glob("*.c")) + sorted(app.glob("*.S"))
        if app.name in progs:
            sys.exit(f"build_sw: program name '{app.name}' is not unique")
        progs[app.name] = sources + APP_RUNTIME
    return progs


def bin_to_words(data: bytes) -> list[int]:
    """Little-endian 32-bit words, the last one zero-padded."""
    data += bytes(-len(data) % 4)
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]


def words_to_hex(words: list[int]) -> str:
    return "".join(f"{w:08X}\n" for w in words)


def words_to_vhdl_package(words: list[int], source: str) -> str:
    body = ",\n".join(
        "    " + ", ".join(f'x"{w:08X}"' for w in words[i:i + 6])
        for i in range(0, len(words), 6))
    return (
        f"-- Generated by scripts/build_sw.py from {source}; do not edit.\n"
        "--\n"
        "-- Program image for synthesis. The testbenches read the .hex files\n"
        "-- instead, so the RTL itself contains no file I/O.\n"
        "\n"
        "library ieee;\n"
        "use ieee.std_logic_1164.all;\n"
        "\n"
        "use work.rv32i_pkg.all;\n"
        "\n"
        "package rom_image_pkg is\n"
        "\n"
        f"  constant ROM_IMAGE : word_array_t(0 to {len(words) - 1}) := (\n"
        f"{body}\n"
        "  );\n"
        "\n"
        "end package rom_image_pkg;\n")


def executable_words(elf: bytes) -> list[int]:
    """All 32-bit words of the executable sections of a little-endian ELF32."""
    if elf[:4] != b"\x7fELF" or elf[4] != 1 or elf[5] != 1:
        raise ValueError("not a little-endian ELF32 file")
    shoff = struct.unpack_from("<I", elf, 0x20)[0]
    shentsize, shnum = struct.unpack_from("<HH", elf, 0x2E)
    words = []
    for i in range(shnum):
        (_, sh_type, flags, _, offset, size,
         *_) = struct.unpack_from("<10I", elf, shoff + i * shentsize)
        if flags & SHF_EXECINSTR and sh_type != 8:  # 8 = SHT_NOBITS
            words += [struct.unpack_from("<I", elf, offset + j)[0]
                      for j in range(0, size - size % 4, 4)]
    return words


def check_rv32i(name: str, elf: Path) -> None:
    """Fails if the compiler emitted anything outside RV32I (e.g. M or C)."""
    bad = [w for w in executable_words(elf.read_bytes())
           if decode(w).mnemonic == "illegal"]
    if bad:
        sys.exit(f"build_sw: {name}: {len(bad)} non-RV32I words in code, "
                 f"first 0x{bad[0]:08X}")


def build(name: str, sources: list[Path], zig: list[str], work: Path) -> list[int]:
    elf = work / f"{name}.elf"
    binary = work / f"{name}.bin"
    is_c = any(s.suffix == ".c" for s in sources)
    flags = COMMON_FLAGS + (C_FLAGS if is_c else ASM_TEST_FLAGS)
    subprocess.run(zig + ["cc", *flags, *map(str, sources), "-o", str(elf)],
                   check=True)
    subprocess.run(zig + ["objcopy", "-O", "binary", str(elf), str(binary)],
                   check=True)
    # Assembly tests contain deliberate illegal words (zero-filled gaps,
    # the halt_illegal test); compiled code must never.
    if is_c:
        check_rv32i(name, elf)
    data = binary.read_bytes()
    if len(data) > ROM_BYTES:
        sys.exit(f"build_sw: {name} needs {len(data)} bytes, ROM has {ROM_BYTES}")
    return bin_to_words(data)


def build_all(out_images: Path, out_pkg: Path, work: Path) -> None:
    zig = find_zig()
    out_images.mkdir(parents=True, exist_ok=True)
    for name, sources in programs().items():
        words = build(name, sources, zig, work)
        (out_images / f"{name}.hex").write_text(words_to_hex(words), newline="\n")
        print(f"build_sw: {name:<24} {4 * len(words):6d} bytes")
        if name == BOARD_APP:
            out_pkg.write_text(
                words_to_vhdl_package(words, f"sw/apps/{BOARD_APP}"), newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="rebuild into a temporary directory and fail if "
                             "the committed images differ")
    args = parser.parse_args()

    work = ROOT / "build" / "sw"
    work.mkdir(parents=True, exist_ok=True)
    if not args.check:
        build_all(IMAGES, BOARD_PKG, work)
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        tmp_images = Path(tmp) / "images"
        tmp_pkg = Path(tmp) / BOARD_PKG.name
        build_all(tmp_images, tmp_pkg, work)
        built = {p.name for p in tmp_images.iterdir()}
        committed = {p.name for p in IMAGES.glob("*.hex")}
        stale = sorted(n for n in built
                       if n not in committed
                       or not filecmp.cmp(tmp_images / n, IMAGES / n, shallow=False))
        stale += sorted(f"{n} (no source)" for n in committed - built)
        if not BOARD_PKG.exists() or not filecmp.cmp(tmp_pkg, BOARD_PKG, shallow=False):
            stale.append(str(BOARD_PKG.relative_to(ROOT)))
    if stale:
        print("build_sw: out of date: " + ", ".join(stale))
        return 1
    print("build_sw: committed images are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
